import config_types

basic = config_types.ConfigList('basic')
basic.add_config('institution', config_types.StrConfig())
basic.add_config('pipeline', config_types.StrConfig())
basic.add_config('survey', config_types.StrConfig())

processing = config_types.ConfigList('processing')
processing.add_config('base_results_directory', config_types.ReadWriteConfig())
processing.add_config('base_working_directory', config_types.ReadWriteConfig())
processing.add_config('default_zaplist', config_types.FileConfig())
processing.add_config('zaplistdir', config_types.DirConfig())
processing.add_config('job_basename', config_types.StrConfig())
processing.add_config('resource_list', config_types.StrConfig())
processing.add_config('delete_rawdata', config_types.BoolConfig())
processing.add_config('sleep', config_types.IntConfig())
processing.add_config('rawdata_directory', config_types.DirConfig())
processing.add_config('max_jobs_running', config_types.IntConfig())
processing.add_config('max_attempts', config_types.IntConfig())
processing.add_config('QueueManagerClass', config_types.QManagerConfig())

background = config_types.ConfigList('background')
background.add_config('screen_output', config_types.BoolConfig())
background.add_config('jobtracker_db', config_types.FileConfig())

email = config_types.ConfigList('email')
email.add_config('enabled', config_types.BoolConfig())
email.add_config('smtp_host', config_types.StrConfig())
email.add_config('smtp_username', config_types.StrConfig())
email.add_config('smtp_password', config_types.StrConfig())
email.add_config('recipient', config_types.StrConfig())
email.add_config('sender', config_types.StrOrNoneConfig())
email.add_config('send_on_failures', config_types.BoolConfig())
email.add_config('send_on_terminal_failures', config_types.BoolConfig())

download = config_types.ConfigList('download')
download.add_config('api_service_url', config_types.StrConfig())
download.add_config('api_username', config_types.StrConfig())
download.add_config('api_password', config_types.StrConfig())
download.add_config('temp', config_types.DirConfig())
download.add_config('space_to_use', config_types.IntConfig())
download.add_config('numdownloads', config_types.IntConfig())
download.add_config('numrestores', config_types.IntConfig())
download.add_config('numretries', config_types.IntConfig())

upload = config_types.ConfigList('upload')
upload.add_config('version_num', config_types.StrConfig())

commondb = config_types.ConfigList('commondb')
commondb.add_config('username', config_types.StrConfig())
commondb.add_config('password', config_types.StrConfig())
commondb.add_config('host', config_types.StrConfig())
